### ISSUE TITLE
Bug---未完全遵循leader中要求3

### ISSUE THREAD

**Issue by chentaiyue** [s09g/raft-go#10]
https://github.com/s09g/raft-go/blob/10b073d519a3f9bbbf842cdfeb41ce9507b359e7/src/raft/append_entry.go#L29
在原文中，"If last log index ≥ nextIndex for a follower: send"，在实现时把=舍去了。   虽然heartbeat保证了仅存在一条更新时，也可以使其它的server完成更新，但还是和原文有一些差异。

**Comment by s09g** [comment]
Make sense. Thanks for the heads-up!
